mod consolidation;
mod decay;
mod entry;
mod error;
pub mod frontmatter;
pub mod page_frontmatter;
mod pipeline;
mod retriever;
mod store;
mod vector;
mod wiki;

pub use consolidation::{ConsolidateStats, Consolidator, ConsolidatorConfig, LlmSummarizer};
pub use decay::apply_decay;
pub use entry::{ImportanceLevel, MemoryEntry, MemoryType};
pub use error::MemoryError;
pub use pipeline::{build_embed_meta, build_embed_text, EmbedJob, Pipeline};
pub use retriever::{HybridRetriever, KeywordRetriever, MemoryRetriever, RetrievedMemory};
pub use store::{MemoryEntryMeta, MemorySearchEntry, MemoryStore, Store};
pub use vector::{cosine_similarity, Embedder, VectorResult, VectorStorer};
pub use wiki::{MemorySchema, PageSearchResult, PageStore, WikiPage};
