mod glob;
mod grep;
mod list_dir;
pub(crate) mod path;
mod read;
mod write;

pub use self::glob::GlobTool;
pub use grep::GrepTool;
pub use list_dir::ListDirTool;
pub use read::FileReadTool;
pub use write::FileWriteTool;

/// Directories to skip during filesystem traversal.
const SKIP_DIRS: &[&str] = &[".git", "node_modules", "vendor", ".hg", "target"];

// Re-export path utilities so submodules can use `super::resolve_path` etc.
pub(crate) use path::{enforce_path_jail, resolve_path};

/// Sanitize a glob pattern that may have been generated by an LLM.
///
/// Fixes:
/// - Unclosed braces: `*.{ts,tsx` → `*.{ts,tsx}`
/// - Auto-prefix: `*.rs` → `**/*.rs` when no path separator present
pub(crate) fn sanitize_glob(pattern: &str) -> String {
    let mut result = pattern.to_string();

    // Fix unclosed braces
    let opens = result.chars().filter(|&c| c == '{').count();
    let closes = result.chars().filter(|&c| c == '}').count();
    if opens > closes {
        for _ in 0..(opens - closes) {
            result.push('}');
        }
    }

    // Auto-prefix simple patterns without path separators
    if !result.contains('/') && !result.starts_with("**") {
        result = format!("**/{result}");
    }

    result
}
