use ozzie_utils::config::ozzie_path;
use ozzie_utils::i18n as i18n_rt;

use super::i18n;
use super::WakeArgs;

pub async fn run(args: WakeArgs) -> anyhow::Result<()> {
    run_with_path(args, ozzie_path()).await
}

async fn run_with_path(args: WakeArgs, base: std::path::PathBuf) -> anyhow::Result<()> {
    // Register i18n catalogs
    i18n::register_catalogs();

    if args.defaults {
        return run_defaults(base).await;
    }

    // Ensure base directory exists
    if !base.exists() {
        std::fs::create_dir_all(&base)?;
    }
    for dir in ["sessions", "tasks", "skills", "memory", "logs", "plugins"] {
        std::fs::create_dir_all(base.join(dir))?;
    }

    // Run wizard with stdin collector
    let mut collector = crate::config_input::StdinCollector::new();
    let cfg = match super::orchestrator::run(&mut collector, &base).await? {
        Some(c) => c,
        None => {
            println!("{}", i18n_rt::t("wizard.cancel"));
            return Ok(());
        }
    };

    // Write config
    println!();
    println!("{}", i18n_rt::t("wizard.confirm.applying"));
    let json = serde_json::to_string_pretty(&cfg)?;
    let content = format!("// Ozzie configuration — generated by `ozzie wake`\n{json}\n");
    std::fs::write(base.join("config.jsonc"), content)?;
    println!("{}", i18n_rt::t("wizard.confirm.done"));

    // Getting to know each other
    let lang = cfg
        .agent
        .preferred_language
        .as_deref()
        .filter(|s| !s.is_empty());
    if let Err(e) = super::acquaintance::run(&base, lang).await {
        eprintln!("Acquaintance step failed: {e}");
        eprintln!("You can re-run it later with: ozzie wake");
    }

    println!();
    println!("{}", i18n_rt::t("wizard.done.title"));
    println!("{}", i18n_rt::t("wizard.done.gateway_hint"));
    println!("  ozzie gateway");
    println!();
    println!("{}", i18n_rt::t("wizard.done.ask_hint"));
    println!("  ozzie ask \"Hello, Ozzie!\"");

    Ok(())
}

/// Fast path: skip all prompts, apply sensible defaults.
async fn run_defaults(base: std::path::PathBuf) -> anyhow::Result<()> {
    println!("Ozzie setup (defaults)");
    println!("======================");
    println!();

    if !base.exists() {
        std::fs::create_dir_all(&base)?;
    }
    for dir in ["sessions", "tasks", "skills", "memory", "logs", "plugins"] {
        std::fs::create_dir_all(base.join(dir))?;
    }

    let enc_svc = crate::crypt::AgeEncryptionService::new(&base);
    if !enc_svc.is_available() {
        enc_svc.generate()?;
    }

    let config_path = base.join("config.jsonc");
    if !config_path.exists() {
        let config = r#"{
  // Ozzie configuration — generated by `ozzie wake --defaults`
  "models": {
    "default": "anthropic",
    "providers": {
      "anthropic": {
        "driver": "anthropic",
        "model": "claude-sonnet-4-20250514"
      }
    }
  },
  "gateway": {
    "host": "127.0.0.1",
    "port": 18420
  }
}
"#;
        std::fs::write(&config_path, config)?;
    }

    println!("Setup complete! Start the gateway with:");
    println!("  ozzie gateway");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn wake_defaults() {
        let dir = tempfile::tempdir().unwrap();
        let args = WakeArgs { defaults: true };
        run_with_path(args, dir.path().to_path_buf()).await.unwrap();

        assert!(dir.path().join("config.jsonc").exists());
        assert!(dir.path().join(".age").join("current.key").exists());
        assert!(dir.path().join("sessions").exists());
    }

    #[tokio::test]
    async fn wake_defaults_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let args = WakeArgs { defaults: true };
        run_with_path(args, dir.path().to_path_buf()).await.unwrap();
        let args2 = WakeArgs { defaults: true };
        run_with_path(args2, dir.path().to_path_buf()).await.unwrap();
    }
}
